/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.DrustvenaIgra;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author ilija
 */
public class DodajStavkuForma extends javax.swing.JFrame {

    /**
     * Creates new form DodajStavkuForma
     */
    public DodajStavkuForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtRacunId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKolicina = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbDrustveneIgre = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        btnKreiraj = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Racun id:");

        jLabel2.setText("RB:");

        jLabel3.setText("Kolicina:");

        jLabel4.setText("Drustvena igra:");

        jLabel5.setText("Cena:");

        btnKreiraj.setText("Kreiraj");

        btnIzmeni.setText("Izmeni");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtKolicina, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtRacunId)
                                        .addComponent(txtRB, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cmbDrustveneIgre, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnKreiraj)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzmeni)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRacunId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbDrustveneIgre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKreiraj)
                    .addComponent(btnIzmeni))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    public void dodavanjeAddActionListener(ActionListener actionListener) {
        btnKreiraj.addActionListener(actionListener);
    }

    public void azuriranjeAddActionListener(ActionListener actionListener) {
        btnIzmeni.addActionListener(actionListener);
    }

    public JButton getBtnIzmeni() {
        return btnIzmeni;
    }

    public void setBtnIzmeni(JButton btnIzmeni) {
        this.btnIzmeni = btnIzmeni;
    }

    public JButton getBtnKreiraj() {
        return btnKreiraj;
    }

    public void setBtnKreiraj(JButton btnKreiraj) {
        this.btnKreiraj = btnKreiraj;
    }

    public JTextField getTxtCena() {
        return txtCena;
    }

    public void setTxtCena(JTextField txtCena) {
        this.txtCena = txtCena;
    }

    public JTextField getTxtKolicina() {
        return txtKolicina;
    }

    public void setTxtKolicina(JTextField txtKolicina) {
        this.txtKolicina = txtKolicina;
    }

    public JTextField getTxtRB() {
        return txtRB;
    }

    public void setTxtRB(JTextField txtRB) {
        this.txtRB = txtRB;
    }

    public JTextField getTxtRacunId() {
        return txtRacunId;
    }

    public void setTxtRacunId(JTextField txtRacunId) {
        this.txtRacunId = txtRacunId;
    }

    public JComboBox<DrustvenaIgra> getCmbDrustveneIgre() {
        return cmbDrustveneIgre;
    }

    public void setCmbDrustveneIgre(JComboBox<DrustvenaIgra> cmbDrustveneIgre) {
        this.cmbDrustveneIgre = cmbDrustveneIgre;
    }

    

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JComboBox<DrustvenaIgra> cmbDrustveneIgre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCena;
    private javax.swing.JTextField txtKolicina;
    private javax.swing.JTextField txtRB;
    private javax.swing.JTextField txtRacunId;
    // End of variables declaration                   
}
